% Compress signal using nondecimated wavelet analysis

% Generated by MATLAB(R) 9.14 and Wavelet Toolbox 6.3.
% Generated on: 01-Mar-2024 10:53:52

function [compressed_signal, energy_lvl_for_compressed] = wvt_compression(signal)
% Perform the decomposition using modwt
wt = modwt(signal,'sym4',4);

numberOfLevelsPlusOne = size(wt,1);

% Compute the energy by level for the decomposition
energyByLevel = 100*sum((wt.^2),2)/sum(wt.^2,'all');

% Thresholds for compressing the imported signal
compressionThresholds = repmat(2.484, 1, numberOfLevelsPlusOne);

% Duplicate coefficients for thresholding
wc = wt;

for idx = 1:numel(compressionThresholds)
    thr = compressionThresholds(idx);
    w = wc(idx,:);
    w(abs(w) <= abs(thr)) = 0;
    wc(idx,:) = w;
end

% Energy by level for the compressed signal
energy_lvl_for_compressed = 100*sum((wc.^2),2)/sum(wc.^2,'all');

% Compute the compressed signal
compressed_signal = imodwt(wc,'sym4');
