% Decomposition coefficients for nondecimated wavelet analysis

% Generated by MATLAB(R) 9.14 and Wavelet Toolbox 6.3.
% Generated on: 01-Mar-2024 10:53:38
function [energyByLevel] = wvt_coeff(signal)
    % Perform the decomposition using modwt
    wt = modwt(signal,'sym4',4);
    
    % Energy by level for the decomposition
    energyByLevel = 100*sum((wt.^2),2)/sum(wt.^2,'all');
end